[package]
name = "pilipili_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.13.0", features = ["macros", "ctrlc_handler"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8.20"
sled = "0.34"
fluent = "0.16"
fluent-bundle = "0.15"
unic-langid = "0.9"
log = "0.4"
fern = "0.7.1"
chrono = "0.4"
colored = "3.0.0"
once_cell = "1.19.0"